### ISSUE TITLE
HP更新依頼

### ISSUE THREAD

**Issue by gbowner** [gb-jp/GB-CORPORATE#8]
@ShotaroTakeshita くん

「01トップページ.html」
から添付ファイルへのリンク設置をお願いします！

（PDFはフォルダ作って下さいー）
[2016-17 年間カレンダー.pdf](https://github.com/gb-jp/GB-CORPORATE/files/260732/2016-17.pdf)

**Comment by ShotaroTakeshita** [comment]
@gbowner 修正してアップしています！

**Comment by gbowner** [comment]
OKです！
